GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjc0LCJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzMzNzQ0OTA4LCJleHAiOjE3MzM3NDQ5Njh9.nIG333oO1iZ4GA5nuvn2g-V5oOb8VOr9f9dk3_7rYyA 
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "liaaaa",
    "email": "tuabd@gmail.com",
    "password": "123ewhw",
    "confirPassword": "123ewhw"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "admin123"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout

###
GET http://localhost:5000/api/users
Content-Type: application/json

{
    "id": 57,
    "name": "ririn",
    "email": "ririnrusmayanti35@gmail.com",
  },