GET http://localhost:5000/users
Authorization: Bearer 
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "liaaaa",
    "email": "tuabd@gmail.com",
    "password": "123ewhw",
    "confirPassword": "123ewhw"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "ryu@gmail.com",
    "password": "veloz333"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout

###
GET http://localhost:5000/api/users
Content-Type: application/json

{
    "id": 57,
    "name": "ririn",
    "email": "ririnrusmayanti35@gmail.com",
  },